import Database from "@ioc:Adonis/Lucid/Database";
import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";

const dataNew = [
  {
    nome_completo: "Departamento de Coordenação, Controlo e Desenvolvimento",
    sigla: "DCCD",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 23,
  },
  {
    nome_completo: "Departamento de Análise e Pesquisa",
    sigla: "DAP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 23,
  },
  {
    nome_completo: "Departamento de Gestão Administrativa",
    sigla: "DGA",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 23,
  },
  {
    nome_completo: "Departamento de Estudos, Informação e Apoio Técnico",
    sigla: "DEIAT",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 23,
  },
  {
    nome_completo:
      "Departamento de Investigação, Prevenção e Repressão Criminal",
    sigla: "DIPRC",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 22,
  },
  {
    nome_completo: "Departamento de Intevenção Operativa",
    sigla: "DIO",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 22,
  },
  {
    nome_completo: "Departamento de Apoio Estratégico e Entrega Controlada",
    sigla: "DAEEC",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 22,
  },
  {
    nome_completo: "Departamentos Provinciais",
    sigla: "DP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 22,
  },
  {
    nome_completo:
      "Departamento de Investigação de Acidentes, Rodoviários, Ferroviários, Aéreos e Marítimos",
    sigla: "DIARFAM",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 25,
  },
  {
    nome_completo:
      "Departamento de Investigação de Acidentes Fluviais, Florestais e Incêndios",
    sigla: "DIAFFI",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 25,
  },
  {
    nome_completo:
      "Departamento de Inteligência de Acidentes, Incêndio, Fogo Posto e de Apoio Técnico",
    sigla: "DIAIFPAT",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 25,
  },
  {
    nome_completo: "Departamentos Provinciais",
    sigla: "DP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 25,
  },
  {
    nome_completo: "Departamento de Pessoal, Quadros e Formação",
    sigla: "DPQF",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 12,
  },
  {
    nome_completo: "Departamento de Estatísticas e Registos",
    sigla: "DER",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 12,
  },
  {
    nome_completo: "Departamento de Precessamento e Remunerações",
    sigla: "DPR",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 12,
  },
  {
    nome_completo: "Departamento de Planificação, Organização e Apoio Técnico",
    sigla: "DPOAT",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 12,
  },
  {
    nome_completo: "Departamento de Contencioso e Acção Social",
    sigla: "DCAS",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 12,
  },
  {
    nome_completo: "Departamentos Provinciais",
    sigla: "DP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 12,
  },
  {
    nome_completo: "Departamento Administrativo",
    sigla: "DA",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 32,
  },
  {
    nome_completo: "Departamento de Contabilidade e Finanças",
    sigla: "DCF",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 32,
  },
  {
    nome_completo: "Departamento de Planeamento Económico",
    sigla: "DPE",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 32,
  },
  {
    nome_completo: "Departamento de Património",
    sigla: "DPA",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 32,
  },
  {
    nome_completo: "Departamentos Provincial",
    sigla: "DP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 32,
  },
  {
    nome_completo: "Departamento de Telecomunicação e Apoio Técnico",
    sigla: "DTAT",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 27,
  },
  {
    nome_completo: "Departamento de Tecnologias de Informação",
    sigla: "DTI",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 27,
  },
  {
    nome_completo: "Departamento de Desenvolvimento de Sistemas",
    sigla: "DTS",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 27,
  },
  {
    nome_completo: "Departamento de Registo, Arquivo e Apoio Administrativo",
    sigla: "DRAAA",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 37,
  },
  {
    nome_completo: "Departamento de Registos Operativos e Prevenção Criminal",
    sigla: "DROPC",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 37,
  },
  {
    nome_completo: "Departamento de Identificação Juridiciária e Criminal",
    sigla: "DIJC",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 37,
  },
  {
    nome_completo:
      "Departamento de Ligação aos Tribunais e Serviços Penitenciários",
    sigla: "DLTSP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 37,
  },
  {
    nome_completo: "Departamento De Educação Patriótica",
    sigla: "DEP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 26,
  },
  {
    nome_completo:
      "Departamento de Cultura, Recreação, Desportos, História e Museologia",
    sigla: "DCRDHM",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 26,
  },
  {
    nome_completo: "Departamento de Direitos Humanos e Organização",
    sigla: "DDHO",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 26,
  },
  {
    nome_completo: "Departamentos Provinciais",
    sigla: "DP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 26,
  },
  {
    nome_completo: "Departamento de Crimes Contra a Saúde Pública",
    sigla: "DCCSP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 36,
  },
  {
    nome_completo:
      "Departamento de Crimes Contra a Ordem Económica e Comércio Internacional",
    sigla: "DCCSP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 36,
  },
  {
    nome_completo:
      "Departamento de Crimes Contra a Propriedade Imaterial e Apoio Técnico",
    sigla: "DCCPIAT",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 36,
  },
  {
    nome_completo:
      "Departamento de Investigação de Crime Contra o Mercado e o do Consumidor",
    sigla: "DICCMC",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 36,
  },
  {
    nome_completo: "Departamentos Provinciais",
    sigla: "DP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 36,
  },
  {
    nome_completo: "Departamebto de Delitos Financeiros Bancários",
    sigla: "DDFB",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 20,
  },
  {
    nome_completo: "Departamebto de Delitos Financeiros não Bancários",
    sigla: "DDFNB",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 20,
  },
  {
    nome_completo: "Departamebto de Delitos Tributários e Apoio Técnico",
    sigla: "DDFNB",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 20,
  },
  {
    nome_completo: "Departamentos Provinciais",
    sigla: "DP",
    user_id: 1,
    activo: true,
    tipo_pessoajuridica_id: 2,
    orgao_comando_provincial: "Departamento",
    descricao: "Criado automaticamente pelo sistema.",
    tipo_estrutura_organica_sigla: "Departamento",
    pessoajuridica_id: 20,
  },
];

function getPessoaObject(input: any) {
  return {
    nome_completo: input.nome_completo,
    tipo: "pj",
    activo: input.activo ? 1 : 0,
    user_id: input.user_id,
    created_at: new Date(),
    updated_at: new Date(),
  };
}

function getPessoaJuridica(input: any, pessoaId: number) {
  return {
    id: pessoaId,
    nif: input.nif,
    sigla: input.sigla,
    user_id: input.user_id,
    pessoajuridica_id: input.pessoajuridica_id,
    tipo_pessoajuridica_id: input.tipo_pessoajuridica_id,
    orgao_comando_provincial: input.orgao_comando_provincial,
    descricao: input.descricao,
    created_at: new Date(),
    updated_at: new Date(),
  };
}

export default class extends BaseSeeder {
  public async run() {
    await Database.transaction(async (trx) => {
      for (const iterator of dataNew) {
        const [pessoaId] = await trx
          .table("pessoas")
          .insert(getPessoaObject(iterator));

        await trx
          .table("pessoajuridicas")
          .insert(getPessoaJuridica(iterator, pessoaId));
      }
    });

    console.log("Órgãos ou comandos registados com sucesso.");
  }
}
