import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import ModuloRepository from "App/Repositories/ModuloRepository";

export default class extends BaseSeeder {
  public async run() {
    // Write your database queries inside the run method

    const repo = new ModuloRepository();
    const dataNew = [
      {
        nome: "Sistema de Gestão de Pessoa e Quadros",
        sigla: "SIGPQ",
        url: null,
        cor: null,
        img: "./../../../assets/img/Admin Settings Male.png",
        versao: 0.1,
        activo: true,
        descricao: "Criado automaticamente pelo sistema.",
        eliminado: false,
      },

      {
        nome: "Portal do Agente",
        sigla: "PA",
        url: null,
        cor: null,
        img: "./../../../assets/img/Administrator Male.png",
        versao: 0.1,
        activo: true,
        descricao: "Criado automaticamente pelo sistema.",
        eliminado: false,
      },
      {
        nome: "Portal Interno da Polícia Nacional",
        sigla: "PIPNA",
        url: null,
        cor: null,
        img: "./../../../assets/img/Police.png",
        versao: 0.1,
        activo: true,
        descricao: "Criado automaticamente pelo sistema.",
        eliminado: false,
      },
      {
        nome: "Sistema de Gestão dos transportes",
        sigla: "SIGT",
        url: null,
        cor: null,
        img: "./../../../assets/img/Public Transportation.png",
        versao: 0.1,
        activo: true,
        descricao: "Criado automaticamente pelo sistema.",
        eliminado: false,
      },
      {
        nome: "Sistema Integrado de Gestão de Processos Jurídicos",
        sigla: "SIGPJ",
        url: null,
        cor: null,
        img: "./../../../assets/img/Scales.png",
        versao: 0.1,
        activo: true,
        descricao: "Criado automaticamente pelo sistema.",
        eliminado: false,
      },
      {
        nome: "Sistema Integrado de Gestão de Ispenção e Atendimento ao Cidadão",
        sigla: "SIGIAC",
        url: null,
        cor: null,
        img: "./../../../assets/img/Detective.png",
        versao: 0.1,
        activo: true,
        descricao: "Criado automaticamente pelo sistema.",
        eliminado: false,
      },
      // {
      //   nome: "Sistema Integrado de Informações policiais",
      //   sigla: "SIINFOP",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Contact.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema Integrado de Gestão Documental",
      //   sigla: "SIGDOC",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Opened Folder.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema Integrado de Ilicitos Penais",
      //   sigla: "SIIP",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Law.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema Integrado de Comunicação",
      //   sigla: "SIGCOM",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Meeting Room.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema Integrado de Gestão de Operações",
      //   sigla: "SIGOP",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Stacked Organizational Chart Highlighted Parent Node.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema Integrado de Gestão de Esquadras",
      //   sigla: "SIGE",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Navigation Toolbar Left.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema Integrado de Gestão de Infrastrutura e Obras",
      //   sigla: "SIGIO",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Constructing.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      {
        nome: "Sistema Integrado de Gestão Informativa",
        sigla: "SIGEF",
        url: null,
        cor: null,
        img: "./../../../assets/img/User Manual.png",
        versao: 0.1,
        activo: true,
        descricao: "Criado automaticamente pelo sistema.",
        eliminado: false,
      },
      // {
      //   nome: "Sistema Integrado de Gestão de Logistica",
      //   sigla: "SIGLOG",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Handcart.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema Integrado de Gestão de Asseguramento das Eleições",
      //   sigla: "SGAE",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Hierarchy.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema de Gestão de Armas e Explusivos",
      //   sigla: "SIGAE",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Submachine Gun.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema Integrado de Gestão de Serviços de saúde",
      //   sigla: "SIGSS",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Doctors Bag.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },

      // {
      //   nome: "Sistema Integrado de Gestão de Orgãos",
      //   sigla: "SIGOC",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Hierarchy.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },

      // {
      //   nome: "Sistema Integrado de Gestão de Códigos",
      //   sigla: "SIGCOD",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Hierarchy.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
      // {
      //   nome: "Sistema Integrado Gestão de Manutenção",
      //   sigla: "SIGM",
      //   url: null,
      //   cor: null,
      //   img: "./../../../assets/img/Hierarchy.png",
      //   versao: 0.1,
      //   activo: true,
      //   descricao: "Criado automaticamente pelo sistema.",
      //   eliminado: false,
      // },
    ];
    await repo.createMany(dataNew);
  }
}