import Database from '@ioc:Adonis/Lucid/Database'
import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'

export default class extends BaseSeeder {
  public async run() {
    const provincias: any = []
    const trx = await Database.transaction()
    try {

      const municipioBengo = [
        {
          nome: 'Ambriz',
          sigla: 'AMB',
          user_id: 2,
          provincia_id: 1,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Aluquém',
          sigla: 'AMB',
          user_id: 2,
          provincia_id: 1,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Bula Atumba',
          sigla: 'BLA',
          user_id: 2,
          provincia_id: 1,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Caxito',
          sigla: 'CXT',
          user_id: 2,
          provincia_id: 1,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Dande',
          sigla: 'DD',
          user_id: 2,
          provincia_id: 1,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Dembos',
          sigla: 'DMB',
          user_id: 2,
          provincia_id: 1,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Nambuangongp',
          sigla: 'NBGG',
          user_id: 2,
          provincia_id: 1,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Pango',
          sigla: 'AMB',
          user_id: 2,
          provincia_id: 1,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },

      ]
      const municipioBenguela = [
        {
          nome: 'Balombo',
          sigla: 'BLB',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Baía Farta',
          sigla: 'BF',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Benguela',
          sigla: 'BG',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Bocio',
          sigla: 'BC',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Caimbombo',
          sigla: 'CBB',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Catumbela',
          sigla: 'CTML',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chongorói',
          sigla: 'CHR',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cubal',
          sigla: 'CBL',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Ganda',
          sigla: 'GD',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Lobito',
          sigla: 'LBT',
          user_id: 2,
          provincia_id: 2,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ]
      const municipioBie = [
        {
          nome: 'Andulo',
          sigla: 'ADL',
          user_id: 2,
          provincia_id: 3,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Camacupa',
          sigla: 'CMCP',
          user_id: 2,
          provincia_id: 3,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Catabola',
          sigla: 'CTBL',
          user_id: 2,
          provincia_id: 3,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chinguar',
          sigla: 'CHG',
          user_id: 2,
          provincia_id: 3,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chitembo',
          sigla: 'CHTMB',
          user_id: 2,
          provincia_id: 3,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuemba',
          sigla: 'CMB',
          user_id: 2,
          provincia_id: 3,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cunhinga',
          sigla: 'CHGA',
          user_id: 2,
          provincia_id: 3,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuíto',
          sigla: 'CT',
          user_id: 2,
          provincia_id: 3,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Nharea',
          sigla: 'NHR',
          user_id: 2,
          provincia_id: 3,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ]

      const municipioCabinda = [
        {
          nome: 'Belize',
          sigla: 'BLZ',
          user_id: 2,
          provincia_id: 4,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Buco-Zau',
          sigla: 'BZ',
          user_id: 2,
          provincia_id: 4,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cabinda',
          sigla: 'CBD',
          user_id: 2,
          provincia_id: 4,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cacongo',
          sigla: 'CCG',
          user_id: 2,
          provincia_id: 4,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        }
      ]

      const municipioCubango = [
        {
          nome: 'Calai',
          sigla: 'CL',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuangar',
          sigla: 'CUGR',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuchi',
          sigla: 'CHI',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuito',
          sigla: 'CUT',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuanavale',
          sigla: 'CNVL',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Dirico',
          sigla: 'DRC',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Mavinga',
          sigla: 'MVG',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Menongue',
          sigla: 'MNG',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Nancova',
          sigla: 'NCV',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Rivungo',
          sigla: 'RVG',
          user_id: 2,
          provincia_id: 5,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ]
      const municipioNorte = [
        {
          nome: 'Ambaca',
          sigla: 'ABC',
          user_id: 2,
          provincia_id: 6,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Banga',
          sigla: 'BNG',
          user_id: 2,
          provincia_id: 6,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Bolongongo',
          sigla: 'BLGG',
          user_id: 2,
          provincia_id: 6,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cazengo',
          sigla: 'CZNGO',
          user_id: 2,
          provincia_id: 6,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Golungo Alto',
          sigla: 'GLGA',
          user_id: 2,
          provincia_id: 6,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Gonguembo',
          sigla: 'GGMB',
          user_id: 2,
          provincia_id: 6,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Lucala',
          sigla: 'LCL',
          user_id: 2,
          provincia_id: 6,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Quiculungo',
          sigla: 'QCLG',
          user_id: 2,
          provincia_id: 6,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Samba Caju',
          sigla: 'SMCJ',
          user_id: 2,
          provincia_id: 6,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        }
      ]
      const municipioSul = [
        {
          nome: 'Amboim',
          sigla: 'ABM',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cassongue',
          sigla: 'CSSG',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cela',
          sigla: 'CL',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Conda',
          sigla: 'CND',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Ebo',
          sigla: 'EBO',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Libolo',
          sigla: 'LBL',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Mussende',
          sigla: 'MSSND',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Porto Amboim',
          sigla: 'PRTA',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Quibala',
          sigla: 'QBL',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Seles',
          sigla: 'SLS',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Sumbe',
          sigla: 'SMB',
          user_id: 2,
          provincia_id: 7,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        }
      ]
      const municipioCunene = [
        {
          nome: 'Cahama',
          sigla: 'CHM',
          user_id: 2,
          provincia_id: 8,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuanhama',
          sigla: 'CNHM',
          user_id: 2,
          provincia_id: 8,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Curoca',
          sigla: 'CRC',
          user_id: 2,
          provincia_id: 8,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuvelai',
          sigla: 'CVL',
          user_id: 2,
          provincia_id: 8,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Namacunde',
          sigla: 'NMCD',
          user_id: 2,
          provincia_id: 8,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Ombaja',
          sigla: 'OBJA',
          user_id: 2,
          provincia_id: 8,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Ondjiva',
          sigla: 'ODJV',
          user_id: 2,
          provincia_id: 8,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ]

      const municipioHuambo = [
        {
          nome: 'Bailundo',
          sigla: 'BLD',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cachiungo',
          sigla: 'CCG',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Caála',
          sigla: 'CAL',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Ecunha',
          sigla: 'ECH',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Huambo',
          sigla: 'HUB',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Londuimbali',
          sigla: 'LDBL',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Longonjo',
          sigla: 'LGJ',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Mungo',
          sigla: 'MNG',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chicala-Cholonga',
          sigla: 'CCLCLG',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chinjeje',
          sigla: 'CHJJ',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Ucuma',
          sigla: 'UCM',
          user_id: 2,
          provincia_id: 9,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        }
      ]
      const municipioHuila = [
        {
          nome: 'Caconda',
          sigla: 'CCND',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cacula',
          sigla: 'CCL',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Caluquembe',
          sigla: 'CLQMB',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chiange',
          sigla: 'CHNG',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chibia',
          sigla: 'CHB',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chicomba',
          sigla: 'CHCMB',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chipindo',
          sigla: 'CHPD',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuvango',
          sigla: 'CVNG',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Humpata',
          sigla: 'HPT',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Jamba',
          sigla: 'JMB',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Matala',
          sigla: 'MTL',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Quilengues',
          sigla: 'QLG',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Quipungo',
          sigla: 'QPG',
          user_id: 2,
          provincia_id: 10,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        }
      ]
      const municipioLuanda = [
        {
          nome: 'Belas',
          sigla: 'BLS',
          user_id: 2,
          provincia_id: 11,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cacuaco',
          sigla: 'CCC',
          user_id: 2,
          provincia_id: 11,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cazenga',
          sigla: 'CZG',
          user_id: 2,
          provincia_id: 11,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Ícolo e Bengo',
          sigla: 'ICLBG',
          user_id: 2,
          provincia_id: 11,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Luanda',
          sigla: 'LD',
          user_id: 2,
          provincia_id: 11,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Kilamba Kiaxi',
          sigla: 'KLMBKX',
          user_id: 2,
          provincia_id: 11,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Quissima',
          sigla: 'QSSM',
          user_id: 2,
          provincia_id: 11,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Talatona',
          sigla: 'TLTN',
          user_id: 2,
          provincia_id: 11,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Viana',
          sigla: 'VN',
          user_id: 2,
          provincia_id: 11,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ]
      const municipioLN = [
        {
          nome: 'Cambulo',
          sigla: 'CML',
          user_id: 2,
          provincia_id: 12,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Capenda-Camulemba',
          sigla: 'CPDCMLMB',
          user_id: 2,
          provincia_id: 12,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Caungula',
          sigla: 'CGL',
          user_id: 2,
          provincia_id: 12,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Chitato',
          sigla: 'CHTT',
          user_id: 2,
          provincia_id: 12,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuango',
          sigla: 'CNG',
          user_id: 2,
          provincia_id: 12,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuílo',
          sigla: 'CUL',
          user_id: 2,
          provincia_id: 12,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Lóvua',
          sigla: 'LV',
          user_id: 2,
          provincia_id: 12,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Lubalo',
          sigla: 'LBL',
          user_id: 2,
          provincia_id: 12,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Xá-Muteba',
          sigla: 'XMTB',
          user_id: 2,
          provincia_id: 12,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ]

      const municipioLS = [
        {
          nome: 'Cacolo',
          sigla: 'CCLO',
          user_id: 2,
          provincia_id: 13,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Dala',
          sigla: 'DL',
          user_id: 2,
          provincia_id: 13,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Muconda',
          sigla: 'MCND',
          user_id: 2,
          provincia_id: 13,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Suarimo',
          sigla: 'SRM',
          user_id: 2,
          provincia_id: 13,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        }
      ]

      const municipioMalanje = [
        {
          nome: 'Cacuso',
          sigla: 'CCSO',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Calandula',
          sigla: 'CLDL',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cambundi-Catembo',
          sigla: 'CMBDCTMB',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cangandala',
          sigla: 'CNGNDL',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Caombo',
          sigla: 'CMB',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cuaba',
          sigla: 'CB',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Nzoji',
          sigla: 'NZJ',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cunda-Dia-Baze',
          sigla: 'CDB',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Luquembo',
          sigla: 'LQMB',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Malanje',
          sigla: 'MLJ',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Marimba',
          sigla: 'MRMB',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Massango',
          sigla: 'MSSNG',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Mucari',
          sigla: 'MCR',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Quela',
          sigla: 'QL',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Quirima',
          sigla: 'QRM',
          user_id: 2,
          provincia_id: 14,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        }
      ]

      const municipioM = [
        {
          nome: 'Alto Zambeze',
          sigla: 'ALTZMB',
          user_id: 2,
          provincia_id: 15,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Bundas',
          sigla: 'BND',
          user_id: 2,
          provincia_id: 15,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Camanongue',
          sigla: 'CMNG',
          user_id: 2,
          provincia_id: 15,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Léua',
          sigla: 'SRM',
          user_id: 2,
          provincia_id: 15,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Luau',
          sigla: 'LUAU',
          user_id: 2,
          provincia_id: 15,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Luacano',
          sigla: 'LCN',
          user_id: 2,
          provincia_id: 15,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Luchazes',
          sigla: 'LCZ',
          user_id: 2,
          provincia_id: 15,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Cameia',
          sigla: 'CMA',
          user_id: 2,
          provincia_id: 15,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Moxico',
          sigla: 'LCN',
          user_id: 2,
          provincia_id: 15,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ]

      const municipioN = [
        {
          nome: 'Libala',
          sigla: 'LBL',
          user_id: 2,
          provincia_id: 16,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Camucuio',
          sigla: 'CMC',
          user_id: 2,
          provincia_id: 16,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Moçâmedes',
          sigla: 'MCMD',
          user_id: 2,
          provincia_id: 16,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Tômbua',
          sigla: 'TMB',
          user_id: 2,
          provincia_id: 16,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Virei',
          sigla: 'VR',
          user_id: 2,
          provincia_id: 16,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        }
      ]

      const municipioU = [
        {
          nome: 'Alto Cauale',
          sigla: 'ALTCL',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Ambuíla',
          sigla: 'AMBL',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Bembe',
          sigla: 'BMB',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Buengas',
          sigla: 'BGS',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Bungo',
          sigla: 'BNG',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Damba',
          sigla: 'DMB',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Milunga',
          sigla: 'MLNG',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Mucaba',
          sigla: 'MCB',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Negage',
          sigla: 'NGG',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Puri',
          sigla: 'PR',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Quimbele',
          sigla: 'QMBL',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Quitexe',
          sigla: 'QTX',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Sanza Pombo',
          sigla: 'SNZPMB',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Songo',
          sigla: 'SNG',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Uíge',
          sigla: 'UG',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Zombo',
          sigla: 'ZMB',
          user_id: 2,
          provincia_id: 17,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ]

      const municipioZ = [
        {
          nome: 'Cuimba',
          sigla: 'CMB',
          user_id: 2,
          provincia_id: 18,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Mabanza',
          sigla: 'MBNZ',
          user_id: 2,
          provincia_id: 18,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Nóqui',
          sigla: 'NQ',
          user_id: 2,
          provincia_id: 18,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Nezeto',
          sigla: 'NZT',
          user_id: 2,
          provincia_id: 18,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Soio',
          sigla: 'SOIO',
          user_id: 2,
          provincia_id: 18,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          nome: 'Tomboco',
          sigla: 'TMBC',
          user_id: 2,
          provincia_id: 18,
          descricao: 'Criado automaticamente pelo sistema.',
          created_at: new Date(),
          updated_at: new Date(),
        }
      ]

      provincias.push(...municipioBengo, ...municipioBenguela, ...municipioBie, ...municipioCabinda, ...municipioCubango, ...municipioCunene, ...municipioHuambo, ...municipioHuila, ...municipioLN, ...municipioLuanda, ...municipioLS, ...municipioMalanje, ...municipioM, ...municipioN, ...municipioU, ...municipioZ)

      for (let item of provincias) {
        await Database.insertQuery().useTransaction(trx).table('municipios').insert(item)
      }
      await trx.commit()
    } catch (e) {
      await trx.commit()
      console.log(e)

    }
  }


}
