import Database from "@ioc:Adonis/Lucid/Database";
import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";

const dataNew = [
  {
    nome: "Ambriz",
    sigla: "AMB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Ambriz, Bengo",
    provincia_id: 1,
  },
  {
    nome: "Bula Atumba",
    sigla: "BUL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bula Atumba, Bengo",
    provincia_id: 1,
  },
  {
    nome: "Dande",
    sigla: "DAN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Dande, Bengo",
    provincia_id: 1,
  },
  {
    nome: "Dembos",
    sigla: "DEM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Dembos, Bengo",
    provincia_id: 1,
  },
  {
    nome: "Nambuangongo",
    sigla: "NAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Nambuangongo, Bengo",
    provincia_id: 1,
  },
  {
    nome: "Pango Aluquém",
    sigla: "PAN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Pango Aluquém, Bengo",
    provincia_id: 1,
  },
  {
    nome: "Balombo",
    sigla: "BAL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Balombo, Benguela",
    provincia_id: 2,
  },
  {
    nome: "Baía Farta",
    sigla: "BAÍ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Baía Farta, Benguela",
    provincia_id: 2,
  },
  {
    nome: "Benguela",
    sigla: "BEN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Benguela, Benguela",
    provincia_id: 2,
  },
  {
    nome: "Bocoio",
    sigla: "BOC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bocoio, Benguela",
    provincia_id: 2,
  },
  {
    nome: "Caimbambo",
    sigla: "CAI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Caimbambo, Benguela",
    provincia_id: 2,
  },
  {
    nome: "Catumbela",
    sigla: "CAT",
    user_id: 1,
    activo: 1,
    descricao: "Município de Catumbela, Benguela",
    provincia_id: 2,
  },
  {
    nome: "Chongorói",
    sigla: "CHO",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chongorói, Benguela",
    provincia_id: 2,
  },
  {
    nome: "Cubal",
    sigla: "CUB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cubal, Benguela",
    provincia_id: 2,
  },
  {
    nome: "Ganda",
    sigla: "GAN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Ganda, Benguela",
    provincia_id: 2,
  },
  {
    nome: "Lobito",
    sigla: "LOB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Lobito, Benguela",
    provincia_id: 2,
  },

  {
    nome: "Andulo",
    sigla: "AND",
    user_id: 1,
    activo: 1,
    descricao: "Município de Andulo, Bié",
    provincia_id: 3,
  },
  {
    nome: "Camacupa",
    sigla: "CAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Camacupa, Bié",
    provincia_id: 3,
  },
  {
    nome: "Catabola",
    sigla: "CAT",
    user_id: 1,
    activo: 1,
    descricao: "Município de Catabola, Bié",
    provincia_id: 3,
  },
  {
    nome: "Chinguar",
    sigla: "CHI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chinguar, Bié",
    provincia_id: 3,
  },
  {
    nome: "Chitembo",
    sigla: "CHT",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chitembo, Bié",
    provincia_id: 3,
  },
  {
    nome: "Cuemba",
    sigla: "CUE",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuemba, Bié",
    provincia_id: 3,
  },
  {
    nome: "Cunhinga",
    sigla: "CUN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cunhinga, Bié",
    provincia_id: 3,
  },
  {
    nome: "Cuíto",
    sigla: "CUÍ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuíto, Bié",
    provincia_id: 3,
  },
  {
    nome: "Nharea",
    sigla: "NHA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Nharea, Bié",
    provincia_id: 3,
  },

  {
    nome: "Belize",
    sigla: "BEL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Belize, Cabinda",
    provincia_id: 4,
  },
  {
    nome: "Buco-Zau",
    sigla: "BUC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Buco-Zau, Cabinda",
    provincia_id: 4,
  },
  {
    nome: "Cabinda",
    sigla: "CAB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cabinda, Cabinda",
    provincia_id: 4,
  },
  {
    nome: "Cacongo",
    sigla: "CAC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cacongo, Cabinda",
    provincia_id: 4,
  },

  {
    nome: "Calai",
    sigla: "CAL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Calai, Cuando Cubango",
    provincia_id: 5,
  },
  {
    nome: "Cuangar",
    sigla: "CUA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuangar, Cuando Cubango",
    provincia_id: 5,
  },
  {
    nome: "Cuchi",
    sigla: "CUC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuchi, Cuando Cubango",
    provincia_id: 5,
  },
  {
    nome: "Cuito Cuanavale",
    sigla: "CUI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuito Cuanavale, Cuando Cubango",
    provincia_id: 5,
  },
  {
    nome: "Dirico",
    sigla: "DIR",
    user_id: 1,
    activo: 1,
    descricao: "Município de Dirico, Cuando Cubango",
    provincia_id: 5,
  },
  {
    nome: "Mavinga",
    sigla: "MAV",
    user_id: 1,
    activo: 1,
    descricao: "Município de Mavinga, Cuando Cubango",
    provincia_id: 5,
  },
  {
    nome: "Menongue",
    sigla: "MEN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Menongue, Cuando Cubango",
    provincia_id: 5,
  },
  {
    nome: "Nancova",
    sigla: "NAN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Nancova, Cuando Cubango",
    provincia_id: 5,
  },
  {
    nome: "Rivungo",
    sigla: "RIV",
    user_id: 1,
    activo: 1,
    descricao: "Município de Rivungo, Cuando Cubango",
    provincia_id: 5,
  },

  {
    nome: "Ambaca",
    sigla: "AMB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Ambaca, Cuanza Norte",
    provincia_id: 6,
  },
  {
    nome: "Banga",
    sigla: "BAN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Banga, Cuanza Norte",
    provincia_id: 6,
  },
  {
    nome: "Bolongongo",
    sigla: "BOL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bolongongo, Cuanza Norte",
    provincia_id: 6,
  },
  {
    nome: "Cambambe",
    sigla: "CAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cambambe, Cuanza Norte",
    provincia_id: 6,
  },
  {
    nome: "Cazengo",
    sigla: "CAZ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cazengo, Cuanza Norte",
    provincia_id: 6,
  },
  {
    nome: "Golungo Alto",
    sigla: "GOL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Golungo Alto, Cuanza Norte",
    provincia_id: 6,
  },
  {
    nome: "Gonguembo",
    sigla: "GON",
    user_id: 1,
    activo: 1,
    descricao: "Município de Gonguembo, Cuanza Norte",
    provincia_id: 6,
  },
  {
    nome: "Lucala",
    sigla: "LUC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Lucala, Cuanza Norte",
    provincia_id: 6,
  },
  {
    nome: "Quiculungo",
    sigla: "QUI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quiculungo, Cuanza Norte",
    provincia_id: 6,
  },
  {
    nome: "Samba Caju",
    sigla: "SAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Samba Caju, Cuanza Norte",
    provincia_id: 6,
  },

  {
    nome: "Amboim",
    sigla: "AMB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Amboim, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Cassongue",
    sigla: "CAS",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cassongue, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Cela",
    sigla: "CEL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cela, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Conda",
    sigla: "CON",
    user_id: 1,
    activo: 1,
    descricao: "Município de Conda, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Ebo",
    sigla: "EBO",
    user_id: 1,
    activo: 1,
    descricao: "Município de Ebo, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Libolo",
    sigla: "LIB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Libolo, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Mussende",
    sigla: "MUS",
    user_id: 1,
    activo: 1,
    descricao: "Município de Mussende, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Porto Amboim",
    sigla: "POR",
    user_id: 1,
    activo: 1,
    descricao: "Município de Porto Amboim, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Quibala",
    sigla: "QUI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quibala, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Quilenda",
    sigla: "QUL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quilenda, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Seles",
    sigla: "SEL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Seles, Cuanza Sul",
    provincia_id: 7,
  },
  {
    nome: "Sumbe",
    sigla: "SUM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Sumbe, Cuanza Sul",
    provincia_id: 7,
  },

  {
    nome: "Cahama",
    sigla: "CAH",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cahama, Cunene",
    provincia_id: 8,
  },
  {
    nome: "Cuanhama",
    sigla: "CUA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuanhama, Cunene",
    provincia_id: 8,
  },
  {
    nome: "Curoca",
    sigla: "CUR",
    user_id: 1,
    activo: 1,
    descricao: "Município de Curoca, Cunene",
    provincia_id: 8,
  },
  {
    nome: "Cuvelai",
    sigla: "CUV",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuvelai, Cunene",
    provincia_id: 8,
  },
  {
    nome: "Namacunde",
    sigla: "NAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Namacunde, Cunene",
    provincia_id: 8,
  },
  {
    nome: "Ombadja",
    sigla: "OMB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Ombadja, Cunene",
    provincia_id: 8,
  },

  {
    nome: "Bailundo",
    sigla: "BAI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bailundo, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Cachiungo",
    sigla: "CAC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cachiungo, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Caála",
    sigla: "CAÁ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Caála, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Ecunha",
    sigla: "ECU",
    user_id: 1,
    activo: 1,
    descricao: "Município de Ecunha, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Huambo",
    sigla: "HUA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Huambo, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Londuimbali",
    sigla: "LON",
    user_id: 1,
    activo: 1,
    descricao: "Município de Londuimbali, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Longonjo",
    sigla: "LOG",
    user_id: 1,
    activo: 1,
    descricao: "Município de Longonjo, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Mungo",
    sigla: "MUN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Mungo, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Chicala-Choloanga",
    sigla: "CHI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chicala-Choloanga, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Chinjenje",
    sigla: "CHN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chinjenje, Huambo",
    provincia_id: 9,
  },
  {
    nome: "Ucuma",
    sigla: "UCU",
    user_id: 1,
    activo: 1,
    descricao: "Município de Ucuma, Huambo",
    provincia_id: 9,
  },

  {
    nome: "Caconda",
    sigla: "CAC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Caconda, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Cacula",
    sigla: "CAU",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cacula, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Caluquembe",
    sigla: "CAL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Caluquembe, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Chiange",
    sigla: "CHG",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chiange, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Chibia",
    sigla: "CHB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chibia, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Chicomba",
    sigla: "CHC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chicomba, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Chipindo",
    sigla: "CHP",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chipindo, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Cuvango",
    sigla: "CUV",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuvango, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Humpata",
    sigla: "HUM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Humpata, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Jamba",
    sigla: "JAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Jamba, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Lubango",
    sigla: "LUB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Lubango, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Matala",
    sigla: "MAT",
    user_id: 1,
    activo: 1,
    descricao: "Município de Matala, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Quilengues",
    sigla: "QUI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quilengues, Huíla",
    provincia_id: 10,
  },
  {
    nome: "Quipungo",
    sigla: "QIP",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quipungo, Huíla",
    provincia_id: 10,
  },

  {
    nome: "Belas",
    sigla: "BEL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Belas, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Cacuaco",
    sigla: "CAC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cacuaco, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Camama",
    sigla: "CAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Camama, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Cazenga",
    sigla: "CAZ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cazenga, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Hoji-ya-Henda",
    sigla: "HOJ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Hoji-ya-Henda, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Ingombota",
    sigla: "ING",
    user_id: 1,
    activo: 1,
    descricao: "Município de Ingombota, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Kilamba",
    sigla: "KIL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Kilamba, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Kilamba Kiaxi",
    sigla: "KIK",
    user_id: 1,
    activo: 1,
    descricao: "Município de Kilamba Kiaxi, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Maianga",
    sigla: "MAI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Maianga, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Mulenvos",
    sigla: "MUL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Mulenvos, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Mussulo",
    sigla: "MUS",
    user_id: 1,
    activo: 1,
    descricao: "Município de Mussulo, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Rangel",
    sigla: "RAN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Rangel, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Samba",
    sigla: "SAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Samba, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Sambizanga",
    sigla: "SAB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Sambizanga, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Talatona",
    sigla: "TAL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Talatona, Luanda",
    provincia_id: 11,
  },
  {
    nome: "Viana",
    sigla: "VIA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Viana, Luanda",
    provincia_id: 11,
  },

  {
    nome: "Cambulo",
    sigla: "CAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cambulo, Lunda Norte",
    provincia_id: 12,
  },
  {
    nome: "Capenda-Camulemba",
    sigla: "CAP",
    user_id: 1,
    activo: 1,
    descricao: "Município de Capenda-Camulemba, Lunda Norte",
    provincia_id: 12,
  },
  {
    nome: "Caungula",
    sigla: "CAU",
    user_id: 1,
    activo: 1,
    descricao: "Município de Caungula, Lunda Norte",
    provincia_id: 12,
  },
  {
    nome: "Chitato",
    sigla: "CHI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Chitato, Lunda Norte",
    provincia_id: 12,
  },
  {
    nome: "Cuango",
    sigla: "CUA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuango, Lunda Norte",
    provincia_id: 12,
  },
  {
    nome: "Cuílo",
    sigla: "CUI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuílo, Lunda Norte",
    provincia_id: 12,
  },
  {
    nome: "Lóvua",
    sigla: "LÓV",
    user_id: 1,
    activo: 1,
    descricao: "Município de Lóvua, Lunda Norte",
    provincia_id: 12,
  },
  {
    nome: "Lubalo",
    sigla: "LUB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Lubalo, Lunda Norte",
    provincia_id: 12,
  },
  {
    nome: "Lucapa",
    sigla: "LUC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Lucapa, Lunda Norte",
    provincia_id: 12,
  },
  {
    nome: "Xá-Muteba",
    sigla: "XÁ-",
    user_id: 1,
    activo: 1,
    descricao: "Município de Xá-Muteba, Lunda Norte",
    provincia_id: 12,
  },

  {
    nome: "Cacolo",
    sigla: "CAC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cacolo, Lunda Sul",
    provincia_id: 13,
  },
  {
    nome: "Dala",
    sigla: "DAL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Dala, Lunda Sul",
    provincia_id: 13,
  },
  {
    nome: "Muconda",
    sigla: "MUC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Muconda, Lunda Sul",
    provincia_id: 13,
  },
  {
    nome: "Saurimo",
    sigla: "SAU",
    user_id: 1,
    activo: 1,
    descricao: "Município de Saurimo, Lunda Sul",
    provincia_id: 13,
  },

  {
    nome: "Cacuso",
    sigla: "CAC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cacuso, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Calandula",
    sigla: "CAL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Calandula, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Cambundi-Catembo",
    sigla: "CAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cambundi-Catembo, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Cangandala",
    sigla: "CAN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cangandala, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Caombo",
    sigla: "CAO",
    user_id: 1,
    activo: 1,
    descricao: "Município de Caombo, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Cuaba Nzoji",
    sigla: "CUA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuaba Nzoji, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Cunda-Dia-Baze",
    sigla: "CUN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cunda-Dia-Baze, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Luquembo",
    sigla: "LUQ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Luquembo, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Malanje",
    sigla: "MAL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Malanje, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Marimba",
    sigla: "MAR",
    user_id: 1,
    activo: 1,
    descricao: "Município de Marimba, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Massango",
    sigla: "MAS",
    user_id: 1,
    activo: 1,
    descricao: "Município de Massango, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Mucari",
    sigla: "MUC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Mucari, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Quela",
    sigla: "QUE",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quela, Malanje",
    provincia_id: 14,
  },
  {
    nome: "Quirima",
    sigla: "QUI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quirima, Malanje",
    provincia_id: 14,
  },

  {
    nome: "Bundas",
    sigla: "BUN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bundas, Moxico",
    provincia_id: 15,
  },
  {
    nome: "Camanongue",
    sigla: "CAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Camanongue, Moxico",
    provincia_id: 15,
  },
  {
    nome: "Léua",
    sigla: "LÉU",
    user_id: 1,
    activo: 1,
    descricao: "Município de Léua, Moxico",
    provincia_id: 15,
  },
  {
    nome: "Luacano",
    sigla: "LUA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Luacano, Moxico",
    provincia_id: 15,
  },
  {
    nome: "Luchazes",
    sigla: "LUC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Luchazes, Moxico",
    provincia_id: 15,
  },
  {
    nome: "Cameia",
    sigla: "CAE",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cameia, Moxico",
    provincia_id: 15,
  },
  {
    nome: "Moxico",
    sigla: "MOX",
    user_id: 1,
    activo: 1,
    descricao: "Município de Moxico (Luena), Moxico",
    provincia_id: 15,
  },

  {
    nome: "Bibala",
    sigla: "BIB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bibala, Namibe",
    provincia_id: 16,
  },
  {
    nome: "Camucuio",
    sigla: "CAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Camucuio, Namibe",
    provincia_id: 16,
  },
  {
    nome: "Moçâmedes",
    sigla: "MOÇ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Moçâmedes (Namibe), Namibe",
    provincia_id: 16,
  },
  {
    nome: "Tômbua",
    sigla: "TÔM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Tômbua, Namibe",
    provincia_id: 16,
  },
  {
    nome: "Virei",
    sigla: "VIR",
    user_id: 1,
    activo: 1,
    descricao: "Município de Virei, Namibe",
    provincia_id: 16,
  },

  {
    nome: "Alto Cauale",
    sigla: "ALT",
    user_id: 1,
    activo: 1,
    descricao: "Município de Alto Cauale, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Ambuíla",
    sigla: "AMB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Ambuíla, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Bembe",
    sigla: "BEM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bembe, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Buengas",
    sigla: "BUE",
    user_id: 1,
    activo: 1,
    descricao: "Município de Buengas, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Bungo",
    sigla: "BUN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bungo, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Damba",
    sigla: "DAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Damba, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Milunga",
    sigla: "MIL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Milunga, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Mucaba",
    sigla: "MUC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Mucaba, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Negage",
    sigla: "NEG",
    user_id: 1,
    activo: 1,
    descricao: "Município de Negage, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Puri",
    sigla: "PUR",
    user_id: 1,
    activo: 1,
    descricao: "Município de Puri, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Quimbele",
    sigla: "QUI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quimbele, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Quitexe",
    sigla: "QIT",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quitexe, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Sanza Pombo",
    sigla: "SAN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Sanza Pombo, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Songo",
    sigla: "SON",
    user_id: 1,
    activo: 1,
    descricao: "Município de Songo, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Uíge",
    sigla: "UÍG",
    user_id: 1,
    activo: 1,
    descricao: "Município de Uíge, Uíge",
    provincia_id: 17,
  },
  {
    nome: "Zombo",
    sigla: "ZOM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Zombo, Uíge",
    provincia_id: 17,
  },

  {
    nome: "Cuimba",
    sigla: "CUI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuimba, Zaire",
    provincia_id: 18,
  },
  {
    nome: "Mabanza Congo",
    sigla: "MAB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Mbanza Congo, Zaire",
    provincia_id: 18,
  },
  {
    nome: "Nóqui",
    sigla: "NÓQ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Nóqui, Zaire",
    provincia_id: 18,
  },
  {
    nome: "Soyo",
    sigla: "SOY",
    user_id: 1,
    activo: 1,
    descricao: "Município de Soyo, Zaire",
    provincia_id: 18,
  },
  {
    nome: "Tomboco",
    sigla: "TOM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Tomboco, Zaire",
    provincia_id: 18,
  },
  {
    nome: "Nzeto",
    sigla: "NZE",
    user_id: 1,
    activo: 1,
    descricao: "Município de Nzeto, Zaire",
    provincia_id: 18,
  },

  {
    nome: "Alto Zambeze",
    sigla: "ALT",
    user_id: 1,
    activo: 1,
    descricao: "Município de Alto Zambeze, Moxico Leste",
    provincia_id: 20,
  },
  {
    nome: "Bundas",
    sigla: "BUN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bundas, Moxico Leste",
    provincia_id: 20,
  },
  {
    nome: "Camanongue",
    sigla: "CAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Camanongue, Moxico Leste",
    provincia_id: 20,
  },
  {
    nome: "Léua",
    sigla: "LÉU",
    user_id: 1,
    activo: 1,
    descricao: "Município de Léua, Moxico Leste",
    provincia_id: 20,
  },
  {
    nome: "Luau",
    sigla: "LUA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Luau, Moxico Leste",
    provincia_id: 20,
  },
  {
    nome: "Luacano",
    sigla: "LUC",
    user_id: 1,
    activo: 1,
    descricao: "Município de Luacano, Moxico Leste",
    provincia_id: 20,
  },
  {
    nome: "Luchazes",
    sigla: "LUZ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Luchazes, Moxico Leste",
    provincia_id: 20,
  },
  {
    nome: "Cameia",
    sigla: "CAM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cameia, Moxico Leste",
    provincia_id: 20,
  },
  {
    nome: "Moxico",
    sigla: "MOX",
    user_id: 1,
    activo: 1,
    descricao: "Município de Moxico (Luena), Moxico Leste",
    provincia_id: 20,
  },

  {
    nome: "Bom Jesus",
    sigla: "BOM",
    user_id: 1,
    activo: 1,
    descricao: "Município de Bom Jesus, Icolo e Bengo",
    provincia_id: 21,
  },
  {
    nome: "Cabiri",
    sigla: "CAB",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cabiri, Icolo e Bengo",
    provincia_id: 21,
  },
  {
    nome: "Cabo Ledo",
    sigla: "CBO",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cabo Ledo, Icolo e Bengo",
    provincia_id: 21,
  },
  {
    nome: "Calumbo",
    sigla: "CAL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Calumbo, Icolo e Bengo",
    provincia_id: 21,
  },
  {
    nome: "Catete",
    sigla: "CAT",
    user_id: 1,
    activo: 1,
    descricao: "Município de Catete, Icolo e Bengo",
    provincia_id: 21,
  },
  {
    nome: "Quiçama",
    sigla: "QUI",
    user_id: 1,
    activo: 1,
    descricao: "Município de Quiçama, Icolo e Bengo",
    provincia_id: 21,
  },
  {
    nome: "Sequele",
    sigla: "SEQ",
    user_id: 1,
    activo: 1,
    descricao: "Município de Sequele, Icolo e Bengo",
    provincia_id: 21,
  },

  {
    nome: "Mavinga",
    sigla: "MAV",
    user_id: 1,
    activo: 1,
    descricao: "Município de Mavinga, Cuando",
    provincia_id: 22,
  },
  {
    nome: "Nancova",
    sigla: "NAN",
    user_id: 1,
    activo: 1,
    descricao: "Município de Nancova, Cuando",
    provincia_id: 22,
  },
  {
    nome: "Rivungo",
    sigla: "RIV",
    user_id: 1,
    activo: 1,
    descricao: "Município de Rivungo, Cuando",
    provincia_id: 22,
  },
  {
    nome: "Calai",
    sigla: "CAL",
    user_id: 1,
    activo: 1,
    descricao: "Município de Calai, Cuando",
    provincia_id: 22,
  },
  {
    nome: "Cuangar",
    sigla: "CUA",
    user_id: 1,
    activo: 1,
    descricao: "Município de Cuangar, Cuando",
    provincia_id: 22,
  },
  {
    nome: "Dirico",
    sigla: "DIR",
    user_id: 1,
    activo: 1,
    descricao: "Município de Dirico, Cuando",
    provincia_id: 22,
  },
];

function getMunicipio(iterator: any) {
  return {
    ...iterator,
    created_at: new Date(),
    updated_at: new Date(),
  };
}

export default class extends BaseSeeder {
  public async run() {
    await Database.transaction(async (trx) => {
      for (const iterator of dataNew) {
        await trx.table("municipios").insert(getMunicipio(iterator));
      }
    });

    console.log("Provincias registadas com sucesso.");
  }
}
